In [22]:
import pandas as pd

pd.set_option('display.max_columns', None)   # show every column, no ... truncation
pd.set_option('display.width', None)         # don't wrap to a fixed width

In [ ]:
# Skip junk rows
df = pd.read_excel('rollingsales_brooklyn.xlsx', header=4)

In [24]:
df.head(10)

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASEMENT,BUILDING CLASS AT PRESENT,ADDRESS,APARTMENT NUMBER,ZIP CODE,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE
0,3,BATH BEACH,01 ONE FAMILY DWELLINGS,1,6359,32,NaN,S1,1464 86TH STREET,NaN,11228.0,1.0,1.0,2.0,1600.0,3040.0,1931.0,1,S1,3400000,2026-02-04
1,3,BATH BEACH,01 ONE FAMILY DWELLINGS,1,6360,11,NaN,A5,8669 15 AVENUE,NaN,11228.0,1.0,0.0,1.0,1547.0,1428.0,1930.0,1,A5,999000,2026-03-30
2,3,BATH BEACH,01 ONE FAMILY DWELLINGS,1,6363,37,NaN,A5,8611 16 AVENUE,NaN,11214.0,1.0,0.0,1.0,1893.0,1714.0,1930.0,1,A5,970000,2026-01-13
3,3,BATH BEACH,01 ONE FAMILY DWELLINGS,1,6364,4,NaN,A5,1643 BENSON AVENUE,NaN,11214.0,1.0,0.0,1.0,1638.0,1746.0,1930.0,1,A5,0,2025-09-08
4,3,BATH BEACH,01 ONE FAMILY DWELLINGS,1,6364,72,NaN,A5,68 BAY 14TH STREET,NaN,11214.0,1.0,0.0,1.0,1950.0,972.0,1950.0,1,A5,860000,2025-11-24
5,3,BATH BEACH,01 ONE FAMILY DWELLINGS,1,6372,39,NaN,A9,86-29 19 AVENUE,NaN,11214.0,1.0,0.0,1.0,2417.0,1944.0,1930.0,1,A9,1180000,2025-11-19
6,3,BATH BEACH,01 ONE FAMILY DWELLINGS,1,6374,67,NaN,S1,8642 20TH AVENUE,NaN,11214.0,1.0,1.0,2.0,1740.0,3240.0,1925.0,1,S1,1100000,2025-09-03
7,3,BATH BEACH,01 ONE FAMILY DWELLINGS,1,6380,16,NaN,S1,59 BAY 29 STREET,NaN,11214.0,1.0,1.0,2.0,3867.0,3947.0,1920.0,1,S1,0,2026-03-10
8,3,BATH BEACH,01 ONE FAMILY DWELLINGS,1,6380,16,NaN,S1,59 BAY 29 STREET,NaN,11214.0,1.0,1.0,2.0,3867.0,3947.0,1920.0,1,S1,2275000,2026-02-09
9,3,BATH BEACH,01 ONE FAMILY DWELLINGS,1,6408,49,NaN,S1,1965 BATH AVENUE,NaN,11214.0,1.0,1.0,2.0,1596.0,1944.0,1920.0,1,S1,990000,2025-06-13

In [26]:
df.columns = df.columns.str.strip()
df[df['ADDRESS'].str.strip() == '405 SACKETT STREET']

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,EASEMENT,BUILDING CLASS AT PRESENT,ADDRESS,APARTMENT NUMBER,ZIP CODE,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,TAX CLASS AT TIME OF SALE,BUILDING CLASS AT TIME OF SALE,SALE PRICE,SALE DATE
7123,3,CARROLL GARDENS,01 ONE FAMILY DWELLINGS,1,422,50,NaN,A4,405 SACKETT STREET,NaN,11231.0,1.0,0.0,1.0,2000.0,4219.0,1899.0,1,A4,7700000,2025-09-29