In [60]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [61]:
df = pd.read_csv('data/raw_sold.csv')

In [62]:
df.shape

(8232, 29)

In [63]:
df.head()

,web-scraper-start-url,listing-link,listing-link-href,price,bedrooms,bathrooms,area-sqft,address,type,built_in,area,whats_special_tags,whats_special_description,facts_features_text,price_history_date,price_history_event,results-for,price_history_price,price_history_percentage_change,public_tax_history_year,public_tax_history_property_taxes,public_tax_history_property_taxes_percentage_change,public_tax_history_tax_assessment,public_tax_history_tax_assessment_percentage_change,borough,neighborhood,main_image-src,price_history_merged,all_images
0,https://www.zillow.com/brooklyn-new-york-ny-11...,"372 E 9th St, Brooklyn, NY 11218",https://www.zillow.com/homedetails/372-E-9th-S...,"$2,100,000",4,5,"2,830","372 E 9th St, Brooklyn, NY 11218",SingleFamily,1925,null,"Expansive windows, Spacious entry vestibule, L...",Welcome to this meticulously rebuilt home in K...,"<div class=""styles__StyledFadeWrapper-fshdp-8-...","[{""price_history_date"":""7/23/2025""},{""price_hi...","[{""price_history_event"":""Sold""},{""price_histor...",11218 Recently Sold Homes,"[{""price_history_price"":""2100000""},{""price_his...","[{""price_history_percentage_change"":""+5.3""},{""...","[{""public_tax_history_year"":""2025""},{""public_t...","[{""public_tax_history_property_taxes"":""9982""},...","[{""public_tax_history_property_taxes_percentag...","[{""public_tax_history_tax_assessment"":""160920""...","[{""public_tax_history_tax_assessment_percentag...",Brooklyn,Kensington,https://photos.zillowstatic.com/fp/c72c5dddea2...,"[{""price_history_date"":""7/23/2025""},{""price_hi...",https://photos.zillowstatic.com/fp/c72c5dddea2...
1,https://www.zillow.com/brooklyn-new-york-ny-11...,"140 E 2nd St APT 5D, Brooklyn, NY 11218",https://www.zillow.com/homedetails/140-E-2nd-S...,"$615,000",1,1,726,"140 E 2nd St APT 5D, Brooklyn, NY 11218",Cooperative,1940,null,NaN,"140 E 2nd St APT 5D, Brooklyn, NY 11218 is a c...","<div class=""styles__StyledFadeWrapper-fshdp-8-...","[{""price_history_date"":""12/5/2025""},{""price_hi...","[{""price_history_event"":""Sold""},{""price_histor...",11218 Recently Sold Homes,"[{""price_history_price"":""615000""},{""price_hist...","[{""price_history_percentage_change"":""+45.1""}]",[],[],[],[],[],Brooklyn,Windsor Terrace,NaN,"[{""price_history_date"":""12/5/2025""},{""price_hi...",NaN
2,https://www.zillow.com/brooklyn-new-york-ny-11...,"260 Ocean Pkwy APT 3C, Brooklyn, NY 11218",https://www.zillow.com/homedetails/260-Ocean-P...,"$750,000",2,1,"1,000","260 Ocean Pkwy APT 3C, Brooklyn, NY 11218",Cooperative,1930,null,"Serene window view, Stylish sun-soaked living,...",Pre-War Charm Meets Modern Comfort in Prime Ke...,"<div class=""styles__StyledFadeWrapper-fshdp-8-...","[{""price_history_date"":""9/15/2025""},{""price_hi...","[{""price_history_event"":""Sold""},{""price_histor...",11218 Recently Sold Homes,"[{""price_history_price"":""750000""},{""price_hist...","[{""price_history_percentage_change"":""+11.1""},{...","[{""public_tax_history_year"":""2010""},{""public_t...","[{""public_tax_history_property_taxes"":""null""},...",[],"[{""public_tax_history_tax_assessment"":""null""},...","[{""public_tax_history_tax_assessment_percentag...",Brooklyn,Kensington,https://photos.zillowstatic.com/fp/6ce47f3535b...,"[{""price_history_date"":""9/15/2025""},{""price_hi...",https://photos.zillowstatic.com/fp/6ce47f3535b...
3,https://www.zillow.com/brooklyn-new-york-ny-11...,"710 E 3rd St, Brooklyn, NY 11218",https://www.zillow.com/homedetails/710-E-3rd-S...,"$1,500,000",7,2,"2,718","710 E 3rd St, Brooklyn, NY 11218",SingleFamily,1910,"3,802 Lot",NaN,Handyman Special - This property features R 5 ...,"<div class=""styles__StyledFadeWrapper-fshdp-8-...","[{""price_history_date"":""10/6/2025""},{""price_hi...","[{""price_history_event"":""Sold""},{""price_histor...",11218 Recently Sold Homes,"[{""price_history_price"":""1500000""},{""price_his...","[{""price_history_percentage_change"":""+15.4""},{...","[{""public_tax_history_year"":""2025""},{""public_t...","[{""public_tax_history_property_taxes"":""9408""},...","[{""public_tax_history_property_taxes_percentag...","[{""public_tax_history_tax_assessment"":""97020""}...","[{""public_tax_history_tax_assessment_percentag...",Brooklyn,Kensington,https://photos.zillowstatic.com/fp/cd33f7698d0...,"[{""price_history_date"":""10/6/2025""},{""price_hi...",https://photos.zillowstatic.com/fp/cd33f7698d0...
4,https://www.zillow.com/brooklyn-new-york-ny-11...,"152 Stratford Rd, Brooklyn, NY 11218",https://www.zillow.com/homedetails/152-Stratfo...,"$2,150,000",7,5,"3,831","152 Stratford Rd, Brooklyn, NY 11218",SingleFamily,1905,null,"Private fenced backyard, Seven spacious bedroo...",PRICE IMPROVEMENT!!! Unlock the grand potentia...,"<div class=""styles__StyledFadeWrapper-fshdp-8-...","[{""price_history_date"":""10/6/2025""},{""price_hi...","[{""price_history_event"":""Sold""},{""price_histor...",11218 Recently Sold Homes,"[{""price_history_price"":""2150000""},{""price_his...","[{""price_history_percentage_change"":""-4.4""},{""...","[{""public_tax_history_year"":""2025""},{""public_t...","[{""public_tax_history_property_taxes"":""10468""}...","[{""public_tax_history_property_taxes_percentag...","[{""public_tax_history_tax_assessment"":""288180""...","[{""public_tax_history_tax_assessment_percentag...",Brooklyn,Prospect Park South,https://photos.zillowstatic.com/fp/48f379ebb8c...,"[{""price_history_date"":""10/6/2025""},{""price_hi...",https://photos.zillowstatic.com/fp/48f379ebb8c...

In [64]:
df_cleaned = pd.read_csv('data/cleaned_sold.csv')

In [65]:
df_cleaned.shape

(8229, 25)

In [66]:
df_cleaned.head(10)

,listing-link-href,bedrooms,bathrooms,area-sqft,address,type,built_in,lot_area,whats_special_tags,whats_special_description,facts_features_text,price_history_date,price_history_event,price_history_price,public_tax_history_year,public_tax_history_property_taxes,public_tax_history_tax_assessment,borough,neighborhood,main_image-src,all_images,zpid,sold_price,sold_date,days_old
0,https://www.zillow.com/homedetails/372-E-9th-S...,4.0,5.0,2830.0,372 E 9th St,SingleFamily,1925.0,NaN,"Expansive windows, Spacious entry vestibule, L...",Welcome to this meticulously rebuilt home in K...,{'Interior': {'Bedrooms & bathrooms': {'Bedroo...,"[{""price_history_date"":""7/23/2025""},{""price_hi...","[{""price_history_event"":""Sold""},{""price_histor...","[{""price_history_price"":""2100000""},{""price_his...","[{""public_tax_history_year"":""2025""},{""public_t...","[{""public_tax_history_property_taxes"":""9982""},...","[{""public_tax_history_tax_assessment"":""160920""...",Brooklyn,Kensington,https://photos.zillowstatic.com/fp/c72c5dddea2...,https://photos.zillowstatic.com/fp/c72c5dddea2...,30674686,2100000,7/23/2025,344
1,https://www.zillow.com/homedetails/140-E-2nd-S...,1.0,1.0,726.0,140 E 2nd St APT 5D,Cooperative,1940.0,NaN,NaN,"140 E 2nd St APT 5D, Brooklyn, NY 11218 is a c...",{'Interior': {'Bedrooms & bathrooms': {'Bedroo...,"[{""price_history_date"":""12/5/2025""},{""price_hi...","[{""price_history_event"":""Sold""},{""price_histor...","[{""price_history_price"":""615000""},{""price_hist...",[],[],[],Brooklyn,Windsor Terrace,NaN,NaN,418273928,615000,12/5/2025,209
2,https://www.zillow.com/homedetails/260-Ocean-P...,2.0,1.0,1000.0,260 Ocean Pkwy APT 3C,Cooperative,1930.0,NaN,"Serene window view, Stylish sun-soaked living,...",Pre-War Charm Meets Modern Comfort in Prime Ke...,{'Interior': {'Bedrooms & bathrooms': {'Bedroo...,"[{""price_history_date"":""9/15/2025""},{""price_hi...","[{""price_history_event"":""Sold""},{""price_histor...","[{""price_history_price"":""750000""},{""price_hist...","[{""public_tax_history_year"":""2010""},{""public_t...","[{""public_tax_history_property_taxes"":""null""},...","[{""public_tax_history_tax_assessment"":""null""},...",Brooklyn,Kensington,https://photos.zillowstatic.com/fp/6ce47f3535b...,https://photos.zillowstatic.com/fp/6ce47f3535b...,72670045,750000,9/15/2025,290
3,https://www.zillow.com/homedetails/710-E-3rd-S...,7.0,2.0,2718.0,710 E 3rd St,SingleFamily,1910.0,3802.0,NaN,Handyman Special - This property features R 5 ...,{'Interior': {'Bedrooms & bathrooms': {'Bedroo...,"[{""price_history_date"":""10/6/2025""},{""price_hi...","[{""price_history_event"":""Sold""},{""price_histor...","[{""price_history_price"":""1500000""},{""price_his...","[{""public_tax_history_year"":""2025""},{""public_t...","[{""public_tax_history_property_taxes"":""9408""},...","[{""public_tax_history_tax_assessment"":""97020""}...",Brooklyn,Kensington,https://photos.zillowstatic.com/fp/cd33f7698d0...,https://photos.zillowstatic.com/fp/cd33f7698d0...,30675378,1500000,10/6/2025,269
4,https://www.zillow.com/homedetails/152-Stratfo...,7.0,5.0,3831.0,152 Stratford Rd,SingleFamily,1905.0,NaN,"Private fenced backyard, Seven spacious bedroo...",PRICE IMPROVEMENT!!! Unlock the grand potentia...,{'Interior': {'Bedrooms & bathrooms': {'Bedroo...,"[{""price_history_date"":""10/6/2025""},{""price_hi...","[{""price_history_event"":""Sold""},{""price_histor...","[{""price_history_price"":""2150000""},{""price_his...","[{""public_tax_history_year"":""2025""},{""public_t...","[{""public_tax_history_property_taxes"":""10468""}...","[{""public_tax_history_tax_assessment"":""288180""...",Brooklyn,Prospect Park South,https://photos.zillowstatic.com/fp/48f379ebb8c...,https://photos.zillowstatic.com/fp/48f379ebb8c...,30666633,2150000,10/6/2025,269
5,https://www.zillow.com/homedetails/3902-Fort-H...,6.0,2.0,4200.0,3902 Fort Hamilton Pkwy #1,SingleFamily,1899.0,NaN,NaN,Corner mixed use building in prime Borough Par...,{'Interior': {'Bedrooms & bathrooms': {'Bedroo...,"[{""price_history_date"":""9/9/2025""},{""price_his...","[{""price_history_event"":""Sold""},{""price_histor...","[{""price_history_price"":""1650000""},{""price_his...",[],[],[],Brooklyn,Borough Park,https://photos.zillowstatic.com/fp/2648b722306...,https://photos.zillowstatic.com/fp/2648b722306...,439244773,1650000,9/9/2025,296
6,https://www.zillow.com/homedetails/1105-Cortel...,2.0,3.0,1201.0,1105 Cortelyou Rd #301,Condo,2023.0,NaN,"Abundance of natural light, Beautiful southern...",Rarely available and truly one of a kind… welc...,{'Interior': {'Bedrooms & bathrooms': {'Bedroo...,"[{""price_history_date"":""6/18/2026""},{""price_hi...","[{""price_history_event"":""Sold""},{""price_histor...","[{""price_history_price"":""1140000""},{""price_his...","[{""public_tax_history_year"":""2025""},{""public_t...","[{""public_tax_history_property_taxes"":""18661""}...","[{""public_tax_history_tax_assessment"":""120051""...",Brooklyn,Ditmas Park,https://photos.zillowstatic.com/fp/7cfd04c2b6b...,https://photos.zillowstatic.com/fp/7cfd04c2b6b...,2053412903,1140000,6/18/2026,14
7,https://www.zillow.com/homedetails/1202-Cortel...,NaN,NaN,1102.0,1202 Cortelyou Rd,SingleFamily,1930.0,1734.0,NaN,"1202 Cortelyou Rd, Brooklyn, NY 11218 is a sin...",{'Interior': {'Interior area': {'Total interio...,"[{""price_history_date"":""10/24/2025""},{""price_h...","[{""price_history_event"":""Sold""},{""price_histor...","[{""price_history_price"":""1600000""},{""price_his...","[{""public_tax_history_year"":""2025""},{""public_t...","[{""public_tax_history_property_taxes"":""7637""},...","[{""public_tax_history_tax_assessment"":""270000""...",Brooklyn,Ditmas Park,NaN,NaN,30667629,1600000,10/24/2025,251
8,https://www.zillow.com/homedetails/233-Ocean-P...,2.0,2.0,1341.0,233 Ocean Pkwy APT 6A,Condo,2014.0,NaN,"Oversized windows, Premium appliances, Wide-pl...",Make this chic 2 Bed/2 Bath your new home in K...,{'Interior': {'Bedrooms & bathrooms': {'Bedroo...,"[{""price_history_date"":""8/14/2025""},{""price_hi...","[{""price_history_event"":""Sold""},{""price_histor...","[{""price_history_price"":""1065000""},{""price_his...","[{""public_tax_history_year"":""2025""},{""public_t...","[{""public_tax_history_property_taxes"":""15372""}...","[{""public_tax_history_tax_assessment"":""127144""...",Brooklyn,Kensington,https://photos.zillowstatic.com/fp/bbddf8228cc...,https://photos.zillowstatic.com/fp/bbddf8228cc...,245023138,1065000,8/14/2025,322
9,https://www.zillow.com/homedetails/488-Ocean-P...,1.0,1.0,NaN,488 Ocean Pkwy APT 3F,Cooperative,1958.0,NaN,NaN,"488 Ocean Pkwy APT 3F, Brooklyn, NY 11218 is a...",{'Interior': {'Bedrooms & bathrooms': {'Bedroo...,"[{""price_history_date"":""7/3/2025""}]","[{""price_history_event"":""Sold""}]","[{""price_history_price"":""400000""}]",[],[],[],Brooklyn,Kensington,NaN,NaN,250731919,400000,7/3/2025,364

In [69]:
df_photos = pd.read_csv('data/photo_links.csv')

In [70]:
df_photos.head(10)

,Unnamed: 0,main_image-src,all_images,zpid
0,0,https://photos.zillowstatic.com/fp/c72c5dddea2...,https://photos.zillowstatic.com/fp/c72c5dddea2...,30674686
1,1,NaN,NaN,418273928
2,2,https://photos.zillowstatic.com/fp/6ce47f3535b...,https://photos.zillowstatic.com/fp/6ce47f3535b...,72670045
3,3,https://photos.zillowstatic.com/fp/cd33f7698d0...,https://photos.zillowstatic.com/fp/cd33f7698d0...,30675378
4,4,https://photos.zillowstatic.com/fp/48f379ebb8c...,https://photos.zillowstatic.com/fp/48f379ebb8c...,30666633
5,5,https://photos.zillowstatic.com/fp/2648b722306...,https://photos.zillowstatic.com/fp/2648b722306...,439244773
6,6,https://photos.zillowstatic.com/fp/7cfd04c2b6b...,https://photos.zillowstatic.com/fp/7cfd04c2b6b...,2053412903
7,7,NaN,NaN,30667629
8,8,https://photos.zillowstatic.com/fp/bbddf8228cc...,https://photos.zillowstatic.com/fp/bbddf8228cc...,245023138
9,9,NaN,NaN,250731919